"""Render Copilot custom agents for the three delegation roles.

    python3 scripts/copilot_agents.py          # write com.github.copilot/agents/
    python3 scripts/copilot_agents.py --check  # exit 1 if the committed files are stale

Sources are scripts/copilot_agents/<name>.md. Two tokens pull text out of
delegating-tasks-with-review-gates' own dispatch templates, so an agent can
never drift from the skill it serves:

    {{IMPLEMENTER_DISCIPLINE}}  implementer-prompt.md's prompt, from
                                "## You Do Not Dispatch Subagents" to its end
    {{REVIEWER_SHARED}}         reviewer-prompt.md's shared reviewer discipline
                                (its first fenced block)

Copilot CLI reads *.agent.md from a plugin's agents directory and offers each
as an agent_type of its task tool. A template whose shape changes fails the
render loudly rather than shipping an agent with a hole in it.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scripts" / "copilot_agents"
OUT = ROOT / "com.github.copilot" / "agents"
REF = ROOT / "skills" / "delegating-tasks-with-review-gates" / "reference"
HEADER = ("<!-- Generated by scripts/copilot_agents.py from scripts/copilot_agents/{name}.md"
          " and delegating-tasks-with-review-gates/reference/. Edit those, not this file. -->")
# Copilot's documented ceiling for an agent profile's body.
MAX_BODY = 30_000


class TemplateShapeError(RuntimeError):
    pass


def fenced_blocks(text: str) -> list[str]:
    blocks, cur = [], None
    for line in text.split("\n"):
        if line.startswith("```"):
            if cur is None:
                cur = []
            else:
                blocks.append("\n".join(cur))
                cur = None
        elif cur is not None:
            cur.append(line)
    return blocks


def dispatch_prompt(block: str, label: str) -> str:
    lines = block.split("\n")
    for i, line in enumerate(lines):
        if re.fullmatch(r"\s*prompt:\s*\|\s*", line):
            return "\n".join(re.sub(r"^ {4}", "", x) for x in lines[i + 1:]).rstrip()
    raise TemplateShapeError(f"{label}: no 'prompt: |' line in its first fenced block")


def tokens() -> dict[str, str]:
    imp = dispatch_prompt(fenced_blocks((REF / "implementer-prompt.md").read_text(encoding="utf-8"))[0],
                          "implementer-prompt.md")
    cut = imp.find("## You Do Not Dispatch Subagents")
    if cut < 0:
        raise TemplateShapeError("implementer-prompt.md: '## You Do Not Dispatch Subagents' not found")
    discipline = imp[cut:].replace("[REPORT_FILE]", "the report file named in your task prompt")
    for heading in ("## Before Reporting Back: Self-Review", "## Report Format"):
        if heading not in discipline:
            raise TemplateShapeError(f"implementer-prompt.md: '{heading}' not found")
    shared = fenced_blocks((REF / "reviewer-prompt.md").read_text(encoding="utf-8"))[0].rstrip()
    for heading in ("## You Do Not Dispatch Subagents", "## Do Not Trust the Report", "## Calibration"):
        if heading not in shared:
            raise TemplateShapeError(f"reviewer-prompt.md shared block: '{heading}' not found")
    return {"{{IMPLEMENTER_DISCIPLINE}}": discipline, "{{REVIEWER_SHARED}}": shared}


def render() -> dict[str, str]:
    toks = tokens()
    out = {}
    for src in sorted(SRC.glob("*.md")):
        text = src.read_text(encoding="utf-8").replace("\r\n", "\n")
        text = text.replace("{{GENERATED_HEADER}}", HEADER.format(name=src.stem))
        for key, value in toks.items():
            text = text.replace(key, value)
        left = re.search(r"\{\{[A-Z_]+\}\}", text)
        if left:
            raise TemplateShapeError(f"{src.name}: unresolved token {left.group(0)}")
        body = text.split("\n---\n", 1)[1] if text.startswith("---\n") else text
        if len(body) > MAX_BODY:
            raise TemplateShapeError(f"{src.name}: body is {len(body)} chars, over Copilot's {MAX_BODY}")
        out[f"{src.stem}.agent.md"] = text.rstrip("\n") + "\n"
    return out


def main(argv: list[str]) -> int:
    rendered = render()
    if "--check" in argv:
        stale = [n for n, t in rendered.items()
                 if not (OUT / n).is_file() or (OUT / n).read_text(encoding="utf-8") != t]
        extra = [p.name for p in OUT.glob("*.agent.md") if p.name not in rendered] if OUT.is_dir() else []
        for n in stale:
            print(f"stale: com.github.copilot/agents/{n}")
        for n in extra:
            print(f"no source: com.github.copilot/agents/{n}")
        if stale or extra:
            print("run: python3 scripts/copilot_agents.py")
            return 1
        print(f"{len(rendered)} agents up to date")
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in rendered.items():
        (OUT / name).write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote com.github.copilot/agents/{name}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
