"""Integrator: wires content_pipeline's data into templates' HTML and writes
the static site.

    python3 scripts/generate.py                        # local, served at root
    python3 scripts/generate.py --base-path /tbaguette-skills  # GitHub Pages build

Stdlib only. Regenerates docs/index.html, every docs/skills/<slug>/index.html,
and docs/verify-install/index.html (the install command's explanation +
syntax-highlighted source, built from scripts/test_install_command.py at
generation time — see python_highlight.py) from the skill files embedded in
this repo at skills/. That embedded copy is the single source of truth for a
build. All three generated paths should never be hand-edited, since the next
run overwrites them; docs/assets/ is the one thing under docs/ this script
never touches — it's hand-authored CSS/JS/fonts/icons, not generated, and
lives under docs/ only because GitHub Pages serves everything from one
directory.

Output goes under docs/ specifically because that's one of GitHub Pages' two
native source folders (the other being the branch root) — no separate
gh-pages branch or Actions workflow needed to publish it.

The write is atomic: the site is built into a fresh temporary directory
first, and the three generated paths are only swapped into place — each as
its own independent rename, preceded by moving the previous version aside
rather than deleting it first — after every page has been written
successfully. A process killed mid-run (Ctrl-C, OOM, disk full, a CI timeout)
leaves whatever was previously at those three paths untouched rather than a
silent mix of old and new pages with no way to tell which is which, and
never touches docs/assets/ or anything else a human placed under docs/.

Every page also carries the UTC instant this run started (rendered as both
the visitor's local time and UTC in the header) and, per skill, a "new" or
"updated" badge derived from `git status --porcelain -- skills` — see
_changed_skill_slugs(). Both are why this script should always be the very
last step before `git add && git commit`, not a step run speculatively
hours earlier: the timestamp is wall-clock "now," and the badge reflects
whatever is currently uncommitted relative to HEAD, so either one describes
a *different* update if generation and commit drift apart in time.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import content_pipeline
import locales
import python_highlight
import templates

GENERATED_HEADER = "<!-- Generated by scripts/generate.py — do not hand-edit. -->\n"

EXPECTED_SKILL_COUNT = 66

EXPECTED_LOCALE_COUNT = locales.EXPECTED_LOCALE_COUNT


def _default_i18n_root(project_root: Path) -> Path:
    return project_root / "i18n"


def _load_strings(locale: locales.Locale, i18n_root: Path) -> templates.Strings:
    if locale.default:
        return templates.ENGLISH_STRINGS
    path = i18n_root / locale.code / "ui.json"
    if not path.is_file():
        # Not translated yet -- a locale can be fully routable and live
        # before every chrome string is, see this module's own docstring
        # addendum on sequencing. Falls back silently; a malformed file
        # (wrong key set) below is a hard failure instead, since that's an
        # authoring bug, not an expected missing-content state.
        return templates.ENGLISH_STRINGS
    data = json.loads(path.read_text(encoding="utf-8"))
    try:
        return templates.Strings(**data)
    except TypeError as error:
        raise SystemExit(
            f"{path} exists but doesn't match Strings' exact key set (English's "
            f"key set is the source of truth) — refusing to generate a site with "
            f"a malformed UI catalog for locale {locale.code!r}: {error}"
        ) from error


def _load_verify_install_strings(locale: locales.Locale, i18n_root: Path) -> templates.VerifyInstallStrings:
    if locale.default:
        return templates.ENGLISH_VERIFY_INSTALL_STRINGS
    path = i18n_root / locale.code / "verify-install.json"
    if not path.is_file():
        return templates.ENGLISH_VERIFY_INSTALL_STRINGS
    data = json.loads(path.read_text(encoding="utf-8"))
    try:
        return templates.VerifyInstallStrings(**data)
    except TypeError as error:
        raise SystemExit(
            f"{path} exists but doesn't match VerifyInstallStrings' exact key set "
            f"— refusing to generate a site with a malformed verify-install catalog "
            f"for locale {locale.code!r}: {error}"
        ) from error


def _changed_skill_slugs(project_root: Path) -> dict[str, str]:
    """Maps skill slug -> "new" or "updated" for every skill whose directory
    differs between the working tree and HEAD, scoped to skills/. This is
    deliberately a working-tree-vs-HEAD diff, not HEAD-vs-its-parent:
    generate() always runs as the last step before a commit in this
    project's own workflow (see the module docstring's build/commit/push
    order), so at generation time HEAD is still the *previously* shipped
    state and the working tree holds exactly what's about to ship — this
    is the comparison that answers "what does the update currently being
    prepared touch," which is what a "NEW"/"UPDATED" badge on the site
    should reflect. It also means the badge naturally retires the next time
    the site is generated after that commit lands (working tree catches up
    to HEAD, no diff, nothing flagged) — correct, not a bug: the site should
    only ever flag the single latest update, not an accumulating history.

    Returns {} outside a git checkout or if git isn't on PATH — this is a
    nice-to-have badge, never a build requirement, so it fails open and
    silent rather than blocking generation."""
    git = shutil.which("git")
    if git is None:
        return {}
    result = subprocess.run(
        [git, "status", "--porcelain", "--", "skills"],
        cwd=project_root, capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        return {}

    changed: dict[str, str] = {}
    for line in result.stdout.splitlines():
        if len(line) < 4:
            continue
        status, path = line[:2], line[3:]
        # A renamed/copied entry's path is "old -> new"; the new path is the
        # one that matters here.
        path = path.split(" -> ")[-1]
        parts = Path(path).parts
        if len(parts) < 2 or parts[0] != "skills":
            continue
        slug = parts[1]
        # "new" covers two porcelain shapes, not one: "??" (untracked) is
        # what a fresh `git status` shows, but this project's own
        # pre-commit hook (.githooks/pre-commit) runs generate() *after*
        # `git add -A` has already staged everything — at that point an
        # added file reads "A " instead, and checking only for "??" would
        # silently misclassify every real new skill as merely "updated"
        # the moment it's actually shipped through the normal commit flow.
        # Caught live: the first real skill added after the hook existed
        # showed "Updated" instead of "New" on the deployed site.
        kind = "new" if status == "??" or status[0] == "A" else "updated"
        if slug not in changed or kind == "new":
            changed[slug] = kind
    return changed


def _skills_in_category_order(category: dict, skills: dict) -> list[dict]:
    """Real skill dicts for a category's skill_slugs, in the order the
    category declares them."""
    return [skills[slug] for slug in category.get("skill_slugs", []) if slug in skills]


def _prev_next_and_siblings(
    skill: dict, categories: list[dict], skills: dict
) -> tuple[dict | None, dict | None, list[dict]]:
    """Where a skill sits within its own category's declared order."""
    category = next(
        (c for c in categories if c["slug"] == skill.get("category_slug")), None
    )
    if category is None:
        return None, None, []
    ordered = _skills_in_category_order(category, skills)
    idx = next((i for i, s in enumerate(ordered) if s["slug"] == skill["slug"]), None)
    if idx is None:
        return None, None, ordered
    prev_skill = ordered[idx - 1] if idx > 0 else None
    next_skill = ordered[idx + 1] if idx + 1 < len(ordered) else None
    return prev_skill, next_skill, ordered


def _write(path: Path, html: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(GENERATED_HEADER + html, encoding="utf-8")


def _build_into(output_dir: Path, content: dict, base_path: str, last_updated_utc: str,
                 *, locale: locales.Locale, strings: templates.Strings,
                 verify_strings: templates.VerifyInstallStrings) -> None:
    """Writes one locale's pages into output_dir, which must already exist
    and be empty. Raises on the first failure — the caller is responsible
    for only promoting output_dir's contents once every locale succeeds."""
    categories = content["categories"]
    skills = content["skills"]

    _write(
        output_dir / "index.html",
        templates.render_index(categories, skills, base_path, last_updated_utc=last_updated_utc,
                                locale=locale, strings=strings),
    )

    for skill in skills.values():
        prev_skill, next_skill, siblings = _prev_next_and_siblings(skill, categories, skills)
        html = templates.render_skill_page(
            skill, prev_skill=prev_skill, next_skill=next_skill, siblings=siblings,
            categories=categories, base_path=base_path, last_updated_utc=last_updated_utc,
            locale=locale, strings=strings,
        )
        _write(output_dir / "skills" / skill["slug"] / "index.html", html)

    scripts_dir = Path(__file__).resolve().parent
    install_test_source = (scripts_dir / "test_install_command.py").read_text(encoding="utf-8")
    highlighted_lines = python_highlight.highlight_source(install_test_source)
    verify_html = templates.render_verify_install_page(
        highlighted_lines, categories, base_path, last_updated_utc=last_updated_utc,
        locale=locale, strings=strings, verify_strings=verify_strings,
    )
    _write(output_dir / "verify-install" / "index.html", verify_html)


def generate(project_root: Path, skills_root: Path, *, base_path: str = "",
             only_locale: str | None = None) -> dict:
    """Builds every locale fresh from the embedded skill files (+ i18n/ where
    it exists) and atomically replaces project_root/docs/ with the result.
    Returns the English content dict so a caller (or a test) can assert
    against what was actually generated — this is unchanged from before
    locales existed, since every existing caller only inspects English-
    rooted output.

    only_locale, when given, restricts the build to that one locale's code
    plus English (English is every other locale's fallback source, so it's
    always rebuilt too) — for fast local iteration while translating.
    Omitted (the default), every locale in locales.LOCALES is built, which
    is what a real publish always does.
    """
    if len(locales.LOCALES) != EXPECTED_LOCALE_COUNT:
        raise SystemExit(
            f"expected {EXPECTED_LOCALE_COUNT} locales, locales.LOCALES has "
            f"{len(locales.LOCALES)} — refusing to generate a site against a "
            "schema drift. If a locale was deliberately added or removed, "
            "update EXPECTED_LOCALE_COUNT (scripts/locales.py)."
        )

    if only_locale is None:
        build_locales = list(locales.LOCALES)
    else:
        requested = locales.get_locale(only_locale)
        build_locales = [requested] if requested.default else [requested, locales.DEFAULT_LOCALE]

    i18n_root = _default_i18n_root(project_root)
    changed = _changed_skill_slugs(project_root)
    last_updated_utc = datetime.now(timezone.utc).isoformat(timespec="seconds")

    docs_dir = project_root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    staging_dir = Path(tempfile.mkdtemp(prefix=".docs.build.", dir=project_root))

    english_content: dict | None = None
    swapped_names = ["index.html", "skills", "verify-install", "version.txt"]

    try:
        for locale in build_locales:
            locale_root = None if locale.default else (i18n_root / locale.code)
            content = content_pipeline.build_content(
                str(skills_root),
                locale=(None if locale.default else locale.code),
                locale_root=(str(locale_root) if locale_root else None),
            )
            if locale.default:
                skill_count = len(content["skills"])
                if skill_count != EXPECTED_SKILL_COUNT:
                    raise SystemExit(
                        f"expected {EXPECTED_SKILL_COUNT} skills, content_pipeline "
                        f"produced {skill_count} — refusing to generate a site "
                        "against a schema drift. If a skill was deliberately "
                        "added or removed, update EXPECTED_SKILL_COUNT in this "
                        "file (and the 'to see all N again' count is derived "
                        "automatically, nothing else to change there)."
                    )
                english_content = content

            for slug, skill in content["skills"].items():
                skill["change_status"] = changed.get(slug)

            strings = _load_strings(locale, i18n_root)
            verify_strings = _load_verify_install_strings(locale, i18n_root)
            locale_output_dir = staging_dir if locale.default else (staging_dir / locale.code)
            _build_into(
                locale_output_dir, content, base_path, last_updated_utc,
                locale=locale, strings=strings, verify_strings=verify_strings,
            )
            if not locale.default:
                swapped_names.append(locale.code)

        (staging_dir / "version.txt").write_text(last_updated_utc, encoding="utf-8")
    except Exception:
        shutil.rmtree(staging_dir, ignore_errors=True)
        raise

    for name in swapped_names:
        target = docs_dir / name
        backup = project_root / f".docs.previous.{name}"
        if backup.is_dir():
            shutil.rmtree(backup, ignore_errors=True)
        elif backup.exists():
            backup.unlink()
        if target.exists():
            target.rename(backup)
        (staging_dir / name).rename(target)
        if backup.is_dir():
            shutil.rmtree(backup, ignore_errors=True)
        elif backup.exists():
            backup.unlink()
    shutil.rmtree(staging_dir, ignore_errors=True)

    return english_content


def _default_project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _default_skills_root(project_root: Path) -> Path:
    return project_root / "skills"


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-path",
        default="",
        help=(
            "Prefix for every root-relative asset/nav href, e.g. "
            "/tbaguette-skills for a GitHub Pages project site served from "
            "https://<user>.github.io/tbaguette-skills/. Leave unset for "
            "local serving at the true root."
        ),
    )
    parser.add_argument(
        "--locale",
        default=None,
        help=(
            "Restrict the build to one locale's code (e.g. 'fr'), plus English "
            "(every other locale's fallback source) — for fast local iteration "
            "while translating. Omit to build every locale, which is what a "
            "real publish (and this project's pre-commit hook) always does."
        ),
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    args = _parse_args(sys.argv[1:])
    root = _default_project_root()
    content = generate(root, _default_skills_root(root), base_path=args.base_path, only_locale=args.locale)
    print(
        f"generated {len(content['skills'])} skill pages + index.html "
        f"under {root / 'docs'} (base_path={args.base_path!r}, locale={args.locale!r})"
    )
