"""Integrator: wires content_pipeline's data into templates' HTML and writes
the static site.

    python3 scripts/generate.py                        # local, served at root
    python3 scripts/generate.py --base-path /tbaguette-skills  # GitHub Pages build

Stdlib only. Regenerates docs/index.html, every docs/skills/<slug>/index.html,
docs/verify-install/index.html (the install command's explanation +
syntax-highlighted source, built from scripts/test_install_command.py at
generation time — see python_highlight.py), and docs/getting-started/index.html
(the first session with the library: reload, how skills fire unasked, what to
try, what to check when nothing happens) from the skill files embedded in
this repo at skills/. That embedded copy is the single source of truth for a
build. All four generated paths should never be hand-edited, since the next
run overwrites them; docs/assets/ is the one thing under docs/ this script
never touches — it's hand-authored CSS/JS/fonts/icons, not generated, and
lives under docs/ only because GitHub Pages serves everything from one
directory.

Output goes under docs/ specifically because that's one of GitHub Pages' two
native source folders (the other being the branch root) — no separate
gh-pages branch or Actions workflow needed to publish it.

The write is atomic: the site is built into a fresh temporary directory
first, and the four generated paths are only swapped into place — each as
its own independent rename, preceded by moving the previous version aside
rather than deleting it first — after every page has been written
successfully. A process killed mid-run (Ctrl-C, OOM, disk full, a CI timeout)
leaves whatever was previously at those three paths untouched rather than a
silent mix of old and new pages with no way to tell which is which, and
never touches docs/assets/ or anything else a human placed under docs/.

Every page also carries the UTC instant this run started (rendered as both
the visitor's local time and UTC in the header) and, per skill, a "new" or
"updated" badge that lives for FRESH_WINDOW_HOURS after the change landed —
see _fresh_skills(), which unions recent commit history with whatever the
working tree is about to ship. The landing page additionally gets a "Fresh
from the oven" rail of those skills, newest first.

That timestamp is still why this script should be the very last step before
`git add && git commit` rather than run speculatively hours earlier: it is
wall-clock "now", and the working-tree half of freshness describes an update
that hasn't been committed yet, so both describe a *different* update if
generation and commit drift apart in time.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Callable
from datetime import datetime, timedelta, timezone
from pathlib import Path

import content_pipeline
import githooks
import locales
import python_highlight
import templates

GENERATED_HEADER = "<!-- Generated by scripts/generate.py — do not hand-edit. -->\n"

EXPECTED_SKILL_COUNT = 97

# How long a skill keeps its New/Updated badge after the change landed. The
# site is static, so this boundary is enforced twice and deliberately so:
# here at build time, and again in the browser (site.js), which is what makes
# the window true for a visitor sitting on a page — or loading one from a
# CDN cache — hours after the build that produced it.
FRESH_WINDOW_HOURS = 48

# How far back _recent_skill_commits() will walk looking for changes inside
# that window. git log lists newest-first, so this only ever bites if more
# than this many commits touched skills/ within FRESH_WINDOW_HOURS — and it
# fails toward "not fresh", i.e. a missing badge rather than a wrong one.
_LOG_SCAN_LIMIT = 1000

EXPECTED_LOCALE_COUNT = locales.EXPECTED_LOCALE_COUNT

# Hand-written, newest-first, one entry per shipped change -- see CLAUDE.md.
# This is the half of "what changed" that the Fresh rail structurally cannot
# show: the rail is built from git history scoped to skills/, so a change to
# the site, the install command, or a harness manifest is invisible to it.
UPDATE_NOTES_FILENAME = templates.UPDATE_NOTES_SOURCE_PATH


def _default_i18n_root(project_root: Path) -> Path:
    return project_root / "i18n"


def _load_strings(locale: locales.Locale, i18n_root: Path) -> templates.Strings:
    if locale.default:
        return templates.ENGLISH_STRINGS
    path = i18n_root / locale.code / "ui.json"
    if not path.is_file():
        # Not translated yet -- a locale can be fully routable and live
        # before every chrome string is, see this module's own docstring
        # addendum on sequencing. Falls back silently; a malformed file
        # (wrong key set) below is a hard failure instead, since that's an
        # authoring bug, not an expected missing-content state.
        return templates.ENGLISH_STRINGS
    data = json.loads(path.read_text(encoding="utf-8"))
    try:
        return templates.Strings(**data)
    except TypeError as error:
        raise SystemExit(
            f"{path} exists but doesn't match Strings' exact key set (English's "
            f"key set is the source of truth) — refusing to generate a site with "
            f"a malformed UI catalog for locale {locale.code!r}: {error}"
        ) from error


def _load_verify_install_strings(locale: locales.Locale, i18n_root: Path) -> templates.VerifyInstallStrings:
    if locale.default:
        return templates.ENGLISH_VERIFY_INSTALL_STRINGS
    path = i18n_root / locale.code / "verify-install.json"
    if not path.is_file():
        return templates.ENGLISH_VERIFY_INSTALL_STRINGS
    data = json.loads(path.read_text(encoding="utf-8"))
    try:
        return templates.VerifyInstallStrings(**data)
    except TypeError as error:
        raise SystemExit(
            f"{path} exists but doesn't match VerifyInstallStrings' exact key set "
            f"— refusing to generate a site with a malformed verify-install catalog "
            f"for locale {locale.code!r}: {error}"
        ) from error


def _load_getting_started_strings(locale: locales.Locale, i18n_root: Path) -> templates.GettingStartedStrings:
    """Same contract as _load_verify_install_strings, one file over: absent is
    a silent fall back to English (a locale can route before its per-page prose
    is written), present-but-malformed is a hard failure (that is an authoring
    bug in a file a human just edited, and guessing past it ships a page with
    half its sections silently missing)."""
    if locale.default:
        return templates.ENGLISH_GETTING_STARTED_STRINGS
    path = i18n_root / locale.code / "getting-started.json"
    if not path.is_file():
        return templates.ENGLISH_GETTING_STARTED_STRINGS
    data = json.loads(path.read_text(encoding="utf-8"))
    try:
        return templates.GettingStartedStrings(**data)
    except TypeError as error:
        raise SystemExit(
            f"{path} exists but doesn't match GettingStartedStrings' exact key set "
            f"— refusing to generate a site with a malformed getting-started catalog "
            f"for locale {locale.code!r}: {error}"
        ) from error


def _changed_skill_slugs(project_root: Path) -> dict[str, str]:
    """Maps skill slug -> "new" or "updated" for every skill whose directory
    differs between the working tree and HEAD, scoped to skills/. This is
    deliberately a working-tree-vs-HEAD diff, not HEAD-vs-its-parent:
    generate() always runs as the last step before a commit in this
    project's own workflow (see the module docstring's build/commit/push
    order), so at generation time HEAD is still the *previously* shipped
    state and the working tree holds exactly what's about to ship — this
    is the comparison that answers "what does the update currently being
    prepared touch," which is what a "NEW"/"UPDATED" badge on the site
    should reflect. It also means the badge naturally retires the next time
    the site is generated after that commit lands (working tree catches up
    to HEAD, no diff, nothing flagged) — correct, not a bug: the site should
    only ever flag the single latest update, not an accumulating history.

    Returns {} outside a git checkout or if git isn't on PATH — this is a
    nice-to-have badge, never a build requirement, so it fails open and
    silent rather than blocking generation."""
    git = shutil.which("git")
    if git is None:
        return {}
    result = subprocess.run(
        [git, "status", "--porcelain", "--", "skills"],
        cwd=project_root, capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        return {}

    changed: dict[str, str] = {}
    for line in result.stdout.splitlines():
        if len(line) < 4:
            continue
        status, path = line[:2], line[3:]
        # A renamed/copied entry's path is "old -> new"; the new path is the
        # one that matters here.
        path = path.split(" -> ")[-1]
        parts = Path(path).parts
        if len(parts) < 2 or parts[0] != "skills":
            continue
        slug = parts[1]
        # "new" covers two porcelain shapes, not one: "??" (untracked) is
        # what a fresh `git status` shows, but this project's own
        # pre-commit hook (.githooks/pre-commit) runs generate() *after*
        # `git add -A` has already staged everything — at that point an
        # added file reads "A " instead, and checking only for "??" would
        # silently misclassify every real new skill as merely "updated"
        # the moment it's actually shipped through the normal commit flow.
        # Caught live: the first real skill added after the hook existed
        # showed "Updated" instead of "New" on the deployed site.
        kind = "new" if status == "??" or status[0] == "A" else "updated"
        if slug not in changed or kind == "new":
            changed[slug] = kind
    return changed


def _recent_skill_commits(project_root: Path, *, now: datetime) -> dict[str, dict]:
    """Maps skill slug -> {"status", "at"} for every skill touched by a commit
    inside FRESH_WINDOW_HOURS, newest touch winning.

    This is the half of freshness that _changed_skill_slugs() cannot see. That
    one answers "what is about to ship", which retires the instant the commit
    lands; this one answers "what shipped recently", which is what a badge
    promising a 48-hour window actually needs. The two are unioned in
    _fresh_skills() rather than one replacing the other, because during a
    pre-commit build the change being shipped has no commit to be found by.

    Status describes the *most recent* touch, not the strongest thing that
    happened inside the window: a skill created yesterday and edited an hour
    ago reads Updated, because the badge and the timestamp shown beside it
    have to describe the same event. Reading "New" next to "1 hour ago" tells
    a visitor the skill was created an hour ago, which is a different and
    false claim.

    Deliberately no --since. That flag doesn't just filter, it *stops the
    walk* once it meets an old enough commit, on the assumption that a
    parent is never newer than its child. Commit dates are not actually
    monotonic — rebases, cherry-picks, imports, clock skew and two agents
    committing into one repository all break it — and when they do, --since
    silently truncates history and drops badges that should still be live.
    Caught by check_freshness_window(), whose fixture commits out of order.
    The walk is bounded by _LOG_SCAN_LIMIT instead, and the window is applied
    here in Python against the parsed committer date.

    Merge commits produce no --name-status output and are therefore invisible
    to this. That is fine for a linear history, and anything genuinely
    mid-flight is caught by the working-tree half anyway.

    Returns {} outside a git checkout or if git isn't on PATH — a badge is a
    nice-to-have, never a build requirement, so it fails open and silent."""
    git = shutil.which("git")
    if git is None:
        return {}
    cutoff = now - timedelta(hours=FRESH_WINDOW_HOURS)
    result = subprocess.run(
        [git, "log", f"-n{_LOG_SCAN_LIMIT}", "--no-renames",
         "--format=%x00%cI", "--name-status", "--", "skills"],
        cwd=project_root, capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        return {}

    fresh: dict[str, dict] = {}
    commit_at: str | None = None
    for line in result.stdout.splitlines():
        if line.startswith("\x00"):
            candidate = line[1:].strip()
            parsed = _parse_iso(candidate)
            commit_at = candidate if parsed is not None and parsed >= cutoff else None
            continue
        if commit_at is None or "\t" not in line:
            continue
        code, _, rest = line.partition("\t")
        # A copy entry is "C<score>\told\tnew"; renames are off, so the last
        # field is the path that exists after the commit either way.
        path = rest.split("\t")[-1]
        parts = Path(path).parts
        if len(parts) < 2 or parts[0] != "skills":
            continue
        slug = parts[1]
        # git log walks newest-first, so the first sighting of a slug is its
        # most recent touch — later (older) commits must not overwrite "at".
        entry = fresh.setdefault(slug, {"status": "updated", "at": commit_at})
        # ...and only that newest commit gets to call the skill new. The
        # timestamp comparison is what scopes this: one commit can list
        # several files for the same slug, and all of them are still that
        # same newest commit.
        if entry["at"] == commit_at and code.startswith("A") and path.endswith("SKILL.md"):
            entry["status"] = "new"
    return fresh


def _parse_iso(value: str) -> datetime | None:
    """Timezone-aware datetime from an ISO 8601 string, or None if it isn't
    one. Naive values are rejected rather than assumed UTC — a silently wrong
    timezone would shift a freshness boundary by hours."""
    try:
        parsed = datetime.fromisoformat(value)
    except (TypeError, ValueError):
        return None
    return parsed if parsed.tzinfo is not None else None


def _fresh_skills(project_root: Path, *, now: datetime) -> dict[str, dict]:
    """Every skill currently inside the freshness window, as slug ->
    {"status", "at"}, unioning recent commits with whatever the working tree
    is about to ship."""
    fresh = _recent_skill_commits(project_root, now=now)
    # Uncommitted work is by definition the newest touch, so it replaces any
    # commit-derived entry outright — including its status. A skill added
    # inside the window and edited again now reads Updated, matching the
    # "now" timestamp that lands beside it.
    for slug, status in _changed_skill_slugs(project_root).items():
        fresh[slug] = {"status": status, "at": now.isoformat()}
    return fresh


def _skill_link_resolver(base_path: str, locale: locales.Locale):
    """How content_pipeline turns a slug into an href for this build.

    Lives here rather than in the pipeline because base_path and the locale
    prefix are facts about where this site is being deployed, and body_html
    should stay the same bytes regardless -- see build_content's own note."""
    return lambda slug: templates.skill_url(slug, base_path, locale)


def _update_notes(project_root: Path,
                  resolve_mention: Callable[[str], str | None] | None = None) -> list[dict]:
    """UPDATES.md parsed into entries, or [] if the file isn't there.

    resolve_mention must already be a make_skill_mention_resolver, not a bare
    URL builder: this file's bullets are full of code spans that are not skills
    (`UPDATES.md`, `/fr/`, `scripts/generate.py`), and an unfiltered resolver
    turns every one of them into a link to a page that does not exist.

    Missing is fine and silent -- a clone that has never shipped a change has
    nothing to say, and the section simply doesn't render. Present but
    malformed is a hard failure, on the same reasoning as a malformed ui.json:
    it is an authoring bug in a file a human just edited, and the failure mode
    of guessing is a site that silently drops the entry someone wrote."""
    path = project_root / UPDATE_NOTES_FILENAME
    if not path.is_file():
        return []
    try:
        return content_pipeline.parse_update_notes(
            path.read_text(encoding="utf-8"), resolve_skill_link=resolve_mention
        )
    except ValueError as error:
        raise SystemExit(f"{path}: {error}") from error


def _fresh_order(skills: dict, fresh: dict[str, dict]) -> list[dict]:
    """The fresh skills as real skill dicts, newest change first. Slugs with
    an unparseable timestamp sort last rather than crashing the build."""
    entries = [(slug, meta) for slug, meta in fresh.items() if slug in skills]

    def sort_key(item: tuple[str, dict]) -> tuple[int, float, str]:
        slug, meta = item
        parsed = _parse_iso(meta.get("at", ""))
        if parsed is None:
            return (1, 0.0, slug)
        return (0, -parsed.timestamp(), slug)

    return [skills[slug] for slug, _ in sorted(entries, key=sort_key)]


def _skills_in_category_order(category: dict, skills: dict) -> list[dict]:
    """Real skill dicts for a category's skill_slugs, in the order the
    category declares them."""
    return [skills[slug] for slug in category.get("skill_slugs", []) if slug in skills]


def _prev_next_and_siblings(
    skill: dict, categories: list[dict], skills: dict
) -> tuple[dict | None, dict | None, list[dict]]:
    """Where a skill sits within its own category's declared order."""
    category = next(
        (c for c in categories if c["slug"] == skill.get("category_slug")), None
    )
    if category is None:
        return None, None, []
    ordered = _skills_in_category_order(category, skills)
    idx = next((i for i, s in enumerate(ordered) if s["slug"] == skill["slug"]), None)
    if idx is None:
        return None, None, ordered
    prev_skill = ordered[idx - 1] if idx > 0 else None
    next_skill = ordered[idx + 1] if idx + 1 < len(ordered) else None
    return prev_skill, next_skill, ordered


def _write(path: Path, html: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(GENERATED_HEADER + html, encoding="utf-8")


def _build_into(output_dir: Path, content: dict, base_path: str, last_updated_utc: str,
                 *, locale: locales.Locale, strings: templates.Strings,
                 verify_strings: templates.VerifyInstallStrings,
                 getting_started_strings: templates.GettingStartedStrings,
                 update_notes: list[dict] | None = None,
                 plugin_version: str = "") -> None:
    """Writes one locale's pages into output_dir, which must already exist
    and be empty. Raises on the first failure — the caller is responsible
    for only promoting output_dir's contents once every locale succeeds."""
    categories = content["categories"]
    skills = content["skills"]

    _write(
        output_dir / "index.html",
        templates.render_index(
            categories, skills, base_path, last_updated_utc=last_updated_utc,
            fresh_skills=content.get("fresh_skills", []),
            update_notes=update_notes or [],
            locale=locale, strings=strings, plugin_version=plugin_version,
        ),
    )

    for skill in skills.values():
        prev_skill, next_skill, siblings = _prev_next_and_siblings(skill, categories, skills)
        html = templates.render_skill_page(
            skill, prev_skill=prev_skill, next_skill=next_skill, siblings=siblings,
            categories=categories, base_path=base_path, last_updated_utc=last_updated_utc,
            locale=locale, strings=strings, plugin_version=plugin_version,
        )
        _write(output_dir / "skills" / skill["slug"] / "index.html", html)

    scripts_dir = Path(__file__).resolve().parent
    install_test_source = (scripts_dir / "test_install_command.py").read_text(encoding="utf-8")
    highlighted_lines = python_highlight.highlight_source(install_test_source)
    verify_html = templates.render_verify_install_page(
        highlighted_lines, categories, base_path, last_updated_utc=last_updated_utc,
        locale=locale, strings=strings, verify_strings=verify_strings,
        plugin_version=plugin_version,
    )
    _write(output_dir / "verify-install" / "index.html", verify_html)

    getting_started_html = templates.render_getting_started_page(
        categories, base_path, last_updated_utc=last_updated_utc,
        skill_count=len(skills), locale=locale, strings=strings,
        getting_started=getting_started_strings, plugin_version=plugin_version,
    )
    _write(output_dir / templates.GETTING_STARTED_PATH / "index.html", getting_started_html)


def generate(project_root: Path, skills_root: Path, *, base_path: str = "",
             only_locale: str | None = None) -> dict:
    """Builds every locale fresh from the embedded skill files (+ i18n/ where
    it exists) and atomically replaces project_root/docs/ with the result.
    Returns the English content dict so a caller (or a test) can assert
    against what was actually generated — this is unchanged from before
    locales existed, since every existing caller only inspects English-
    rooted output.

    only_locale, when given, restricts the build to that one locale's code
    plus English (English is every other locale's fallback source, so it's
    always rebuilt too) — for fast local iteration while translating.
    Omitted (the default), every locale in locales.LOCALES is built, which
    is what a real publish always does.
    """
    if len(locales.LOCALES) != EXPECTED_LOCALE_COUNT:
        raise SystemExit(
            f"expected {EXPECTED_LOCALE_COUNT} locales, locales.LOCALES has "
            f"{len(locales.LOCALES)} — refusing to generate a site against a "
            "schema drift. If a locale was deliberately added or removed, "
            "update EXPECTED_LOCALE_COUNT (scripts/locales.py)."
        )

    now = datetime.now(timezone.utc)
    plugin_version = _plugin_version()
    fresh = _fresh_skills(project_root, now=now)
    last_updated_utc = now.isoformat(timespec="seconds")

    if only_locale is None:
        build_locales = list(locales.LOCALES)
    else:
        requested = locales.get_locale(only_locale)
        build_locales = [requested] if requested.default else [requested, locales.DEFAULT_LOCALE]

    i18n_root = _default_i18n_root(project_root)

    docs_dir = project_root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    staging_dir = Path(tempfile.mkdtemp(prefix=".docs.build.", dir=project_root))

    english_content: dict | None = None
    swapped_names = ["index.html", "skills", "verify-install", "getting-started", "version.txt"]

    try:
        for locale in build_locales:
            locale_root = None if locale.default else (i18n_root / locale.code)
            resolve_skill_link = _skill_link_resolver(base_path, locale)
            content = content_pipeline.build_content(
                str(skills_root),
                locale=(None if locale.default else locale.code),
                locale_root=(str(locale_root) if locale_root else None),
                resolve_skill_link=resolve_skill_link,
            )
            # build_content wraps the resolver itself, once per skill, because
            # only it knows whose page each body belongs to and therefore which
            # mention would be a self-link. Nothing owns UPDATES.md's bodies
            # that way, so the wrapping happens here instead -- and it is not
            # optional: unwrapped, every code span in the notes becomes a link,
            # `UPDATES.md` and `/fr/` included.
            update_notes = _update_notes(
                project_root,
                content_pipeline.make_skill_mention_resolver(
                    set(content["skills"]), resolve_skill_link
                ),
            )
            if locale.default:
                skill_count = len(content["skills"])
                if skill_count != EXPECTED_SKILL_COUNT:
                    raise SystemExit(
                        f"expected {EXPECTED_SKILL_COUNT} skills, content_pipeline "
                        f"produced {skill_count} — refusing to generate a site "
                        "against a schema drift. If a skill was deliberately "
                        "added or removed, update EXPECTED_SKILL_COUNT in this "
                        "file (and the 'to see all N again' count is derived "
                        "automatically, nothing else to change there)."
                    )
                english_content = content

            for slug, skill in content["skills"].items():
                entry = fresh.get(slug)
                skill["change_status"] = entry["status"] if entry else None
                skill["change_at"] = entry["at"] if entry else None
            content["fresh_skills"] = _fresh_order(content["skills"], fresh)

            strings = _load_strings(locale, i18n_root)
            verify_strings = _load_verify_install_strings(locale, i18n_root)
            getting_started_strings = _load_getting_started_strings(locale, i18n_root)
            locale_output_dir = staging_dir if locale.default else (staging_dir / locale.code)
            _build_into(
                locale_output_dir, content, base_path, last_updated_utc,
                locale=locale, strings=strings, verify_strings=verify_strings,
                getting_started_strings=getting_started_strings,
                update_notes=update_notes, plugin_version=plugin_version,
            )
            if not locale.default:
                swapped_names.append(locale.code)

        (staging_dir / "version.txt").write_text(last_updated_utc, encoding="utf-8")
    except Exception:
        shutil.rmtree(staging_dir, ignore_errors=True)
        raise

    for name in swapped_names:
        target = docs_dir / name
        backup = project_root / f".docs.previous.{name}"
        if backup.is_dir():
            shutil.rmtree(backup, ignore_errors=True)
        elif backup.exists():
            backup.unlink()
        if target.exists():
            target.rename(backup)
        (staging_dir / name).rename(target)
        if backup.is_dir():
            shutil.rmtree(backup, ignore_errors=True)
        elif backup.exists():
            backup.unlink()
    shutil.rmtree(staging_dir, ignore_errors=True)

    return english_content


def _default_project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _plugin_version() -> str:
    """The published plugin version, shown next to the site wordmark.

    .claude-plugin/plugin.json is the single source of truth for it --
    test_harness_manifests.py already asserts every other manifest matches
    that file, so reading it here keeps the site from becoming a separate
    place the version has to be remembered.

    Deliberately resolved from this script's own location rather than from
    the caller's project_root: project_root is where output goes, and the
    integration tests point it at a scratch directory that has no manifest
    in it. The manifest that describes the plugin being published always
    sits next to scripts/, whatever the output path is."""
    manifest = Path(__file__).resolve().parent.parent / ".claude-plugin" / "plugin.json"
    return json.loads(manifest.read_text(encoding="utf-8"))["version"]


def _default_skills_root(project_root: Path) -> Path:
    return project_root / "skills"


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-path",
        default="",
        help=(
            "Prefix for every root-relative asset/nav href, e.g. "
            "/tbaguette-skills for a GitHub Pages project site served from "
            "https://<user>.github.io/tbaguette-skills/. Leave unset for "
            "local serving at the true root."
        ),
    )
    parser.add_argument(
        "--locale",
        default=None,
        help=(
            "Restrict the build to one locale's code (e.g. 'fr'), plus English "
            "(every other locale's fallback source) — for fast local iteration "
            "while translating. Omit to build every locale, which is what a "
            "real publish (and this project's pre-commit hook) always does."
        ),
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    args = _parse_args(sys.argv[1:])
    root = _default_project_root()
    content = generate(root, _default_skills_root(root), base_path=args.base_path, only_locale=args.locale)
    print(
        f"generated {len(content['skills'])} skill pages + index.html "
        f"under {root / 'docs'} (base_path={args.base_path!r}, locale={args.locale!r})"
    )
