"""Integrator: wires content_pipeline's data into templates' HTML and writes
the static site.

    python3 scripts/generate.py                        # local, served at root
    python3 scripts/generate.py --base-path /tbaguette-skills  # GitHub Pages build

Stdlib only. Regenerates docs/index.html, every docs/skills/<slug>/index.html,
and docs/verify-install/index.html (the install command's explanation +
syntax-highlighted source, built from scripts/test_install_command.py at
generation time — see python_highlight.py) from the skill files embedded in
this repo at skills/. That embedded copy is the single source of truth for a
build. All three generated paths should never be hand-edited, since the next
run overwrites them; docs/assets/ is the one thing under docs/ this script
never touches — it's hand-authored CSS/JS/fonts/icons, not generated, and
lives under docs/ only because GitHub Pages serves everything from one
directory.

Output goes under docs/ specifically because that's one of GitHub Pages' two
native source folders (the other being the branch root) — no separate
gh-pages branch or Actions workflow needed to publish it.

The write is atomic: the site is built into a fresh temporary directory
first, and the three generated paths are only swapped into place — each as
its own independent rename, preceded by moving the previous version aside
rather than deleting it first — after every page has been written
successfully. A process killed mid-run (Ctrl-C, OOM, disk full, a CI timeout)
leaves whatever was previously at those three paths untouched rather than a
silent mix of old and new pages with no way to tell which is which, and
never touches docs/assets/ or anything else a human placed under docs/.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

import content_pipeline
import python_highlight
import templates

GENERATED_HEADER = "<!-- Generated by scripts/generate.py — do not hand-edit. -->\n"

EXPECTED_SKILL_COUNT = 65


def _skills_in_category_order(category: dict, skills: dict) -> list[dict]:
    """Real skill dicts for a category's skill_slugs, in the order the
    category declares them."""
    return [skills[slug] for slug in category.get("skill_slugs", []) if slug in skills]


def _prev_next_and_siblings(
    skill: dict, categories: list[dict], skills: dict
) -> tuple[dict | None, dict | None, list[dict]]:
    """Where a skill sits within its own category's declared order."""
    category = next(
        (c for c in categories if c["slug"] == skill.get("category_slug")), None
    )
    if category is None:
        return None, None, []
    ordered = _skills_in_category_order(category, skills)
    idx = next((i for i, s in enumerate(ordered) if s["slug"] == skill["slug"]), None)
    if idx is None:
        return None, None, ordered
    prev_skill = ordered[idx - 1] if idx > 0 else None
    next_skill = ordered[idx + 1] if idx + 1 < len(ordered) else None
    return prev_skill, next_skill, ordered


def _write(path: Path, html: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(GENERATED_HEADER + html, encoding="utf-8")


def _build_into(output_dir: Path, content: dict, base_path: str) -> None:
    """Writes every page into output_dir, which must already exist and be
    empty. Raises on the first failure — the caller is responsible for only
    promoting output_dir to the real site directory once this returns."""
    categories = content["categories"]
    skills = content["skills"]

    _write(output_dir / "index.html", templates.render_index(categories, skills, base_path))

    for skill in skills.values():
        prev_skill, next_skill, siblings = _prev_next_and_siblings(skill, categories, skills)
        html = templates.render_skill_page(
            skill, prev_skill, next_skill, siblings, categories, base_path
        )
        _write(output_dir / "skills" / skill["slug"] / "index.html", html)

    # test_install_command.py is a fixed sibling of this file — always read
    # from here, never from output_dir/project_root. Those name where the
    # *built site* goes (a throwaway directory in a test, the real repo
    # otherwise); the script being highlighted isn't part of that, the same
    # way `import content_pipeline` above doesn't depend on output_dir either.
    scripts_dir = Path(__file__).resolve().parent
    install_test_source = (scripts_dir / "test_install_command.py").read_text(encoding="utf-8")
    highlighted_lines = python_highlight.highlight_source(install_test_source)
    verify_html = templates.render_verify_install_page(highlighted_lines, categories, base_path)
    _write(output_dir / "verify-install" / "index.html", verify_html)


def generate(project_root: Path, skills_root: Path, *, base_path: str = "") -> dict:
    """Builds content fresh from the embedded skill files and atomically
    replaces project_root/docs/ with the result. Returns the content dict so
    a caller (or a test) can assert against what was actually generated
    rather than re-parsing HTML."""
    content = content_pipeline.build_content(str(skills_root))
    skill_count = len(content["skills"])
    if skill_count != EXPECTED_SKILL_COUNT:
        raise SystemExit(
            f"expected {EXPECTED_SKILL_COUNT} skills, content_pipeline produced "
            f"{skill_count} — refusing to generate a site against a schema drift. "
            "If a skill was deliberately added or removed, update "
            "EXPECTED_SKILL_COUNT in this file (and the 'to see all N again' "
            "count is derived automatically, nothing else to change there)."
        )

    docs_dir = project_root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    staging_dir = Path(tempfile.mkdtemp(prefix=".docs.build.", dir=project_root))
    try:
        _build_into(staging_dir, content, base_path)
    except Exception:
        shutil.rmtree(staging_dir, ignore_errors=True)
        raise

    # Swap in only the paths this function actually owns and just wrote
    # (index.html, skills/, verify-install/) — never the whole of docs_dir.
    # docs/ is also where the site's hand-authored assets/ live (Pages needs
    # everything under one served directory), and a wholesale docs_dir swap
    # would carry those away and delete them along with anything else a
    # human ever adds there that this script doesn't know about.
    for name in ("index.html", "skills", "verify-install"):
        target = docs_dir / name
        backup = project_root / f".docs.previous.{name}"
        if backup.is_dir():
            shutil.rmtree(backup, ignore_errors=True)
        elif backup.exists():
            backup.unlink()
        if target.exists():
            target.rename(backup)
        (staging_dir / name).rename(target)
        if backup.is_dir():
            shutil.rmtree(backup, ignore_errors=True)
        elif backup.exists():
            backup.unlink()
    shutil.rmtree(staging_dir, ignore_errors=True)

    return content


def _default_project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _default_skills_root(project_root: Path) -> Path:
    return project_root / "skills"


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-path",
        default="",
        help=(
            "Prefix for every root-relative asset/nav href, e.g. "
            "/tbaguette-skills for a GitHub Pages project site served from "
            "https://<user>.github.io/tbaguette-skills/. Leave unset for "
            "local serving at the true root."
        ),
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    args = _parse_args(sys.argv[1:])
    root = _default_project_root()
    content = generate(root, _default_skills_root(root), base_path=args.base_path)
    print(
        f"generated {len(content['skills'])} skill pages + index.html "
        f"under {root / 'docs'} (base_path={args.base_path!r})"
    )
